# Generated by Django 5.2.15 on 2026-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='minimal chegara'),
        ),
    ]
