# Generated by Django 5.2.15 on 2026-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_min_stock_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langanmi?"),
        ),
    ]
