# Generated by Django 5.2.15 on 2026-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mijoz_todo_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram @username'),
        ),
    ]
