# Generated by Django 5.2.15 on 2026-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
